#!/bin/bash

# https://github.com/gopherdata/mybinder-go/blob/master/LICENSE.md

set -ex

GOVERS=1.14
GONUMVERS=v0.7.0
GOPHERNOTESVERS=v0.7.1

mkdir -p \
	$HOME/.local/go/$GOVERS \
	$HOME/go

echo "::: install Go ${GOVERS}..."
curl -O -L https://golang.org/dl/go${GOVERS}.linux-amd64.tar.gz
tar -C $HOME/.local/go/$GOVERS -zxf go${GOVERS}.linux-amd64.tar.gz
rm go${GOVERS}.linux-amd64.tar.gz

export GO111MODULE=on
export GOROOT=$HOME/.local/go/$GOVERS/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

## install needed packages
echo "::: installing gophernotes, gonum and graphprac..."
go get golang.org/x/tools/cmd/goimports
go get github.com/gopherdata/gophernotes@${GOPHERNOTESVERS}
go get gonum.org/v1/gonum@${GONUMVERS}
go get gonum.org/v1/gonum/...
go get github.com/kortschak/graphprac
echo "::: installing gophernotes, gonum and graphprac... [done]"

## install the Go kernel
mkdir -p binder/gophernotes
cp $(go env GOPATH)/pkg/mod/github.com/gopherdata/gophernotes@${GOPHERNOTESVERS}/kernel/*.png binder/gophernotes
cat >binder/gophernotes/kernel.json <<EOF
{
    "argv": [
        "$GOPATH/bin/gophernotes",
        "{connection_file}"
    ],
    "display_name": "Go",
    "language": "go",
    "name": "go",
    "env": {
        "GOPATH": "$GOPATH",
        "GOROOT": "$GOROOT",
        "PATH":   "$GOPATH/bin:$GOROOT/bin:$PATH"
    }
}
EOF

jupyter kernelspec install binder/gophernotes --user

rm -rf binder

echo "::: kernel list"
jupyter kernelspec list
